services:
    # ORO REVIEW:
    # This service is never used.
#    entrepids_braintree.braintree.payflow.client.http:
#        class: 'Guzzle\Http\Client'
#        public: false
#        lazy: true
        
    entrepids_braintree.event_listener.callback.braintree:
        class: 'Entrepids\Bundle\BraintreeBundle\EventListener\Callback\BraintreeCheckoutListener'
        lazy: true
        arguments:
            - '@entrepids_braintree.payment_method_provider.braintree'
        calls:
            - ['setLogger', ['@logger']]
        tags:
            # ORO REVIEW:
            # Event with "braintree" suffix will be never dispatched.
            # Why we need this service?
            - { name: kernel.event_listener, event: oro_payment.callback.error, method: onError }
            - { name: kernel.event_listener, event: oro_payment.callback.return, method: onReturn }
