services:
    entrepids_braintree.factory.braintree_config:
        class: 'Entrepids\Bundle\BraintreeBundle\Method\Config\Factory\BraintreeConfigFactory'
        public: false
        arguments:
            - '@oro_security.encoder.mcrypt'        
            - '@oro_locale.helper.localization'
            - '@entrepids_braintree.generator.braintree_config_identifier'

    entrepids_braintree.factory.method.braintree:
        class: 'Entrepids\Bundle\BraintreeBundle\Method\Factory\BraintreePaymentMethodFactory'
        public: false
        arguments:
            - '@entrepids_braintree.method.operation.factory'

    entrepids_braintree.factory.method_view.braintree:
        class: 'Entrepids\Bundle\BraintreeBundle\Method\View\Factory\BraintreePaymentMethodViewFactory'
        public: false
        arguments:
            - '@form.factory'
            - '@oro_payment.provider.payment_transaction'