services:
    entrepids_braintree.form.type.credit_card:
        class: Entrepids\Bundle\BraintreeBundle\Form\Type\CreditCardType
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@security.token_storage'
            - '@entrepids_braintree.braintree.model.adapter.badapter'
            - '@translator'
        tags:
            - { name: form.type, alias: entrepids_braintree_credit_card }
