parameters:
    entrepids_braintree.method.braintree: 'braintree'

services:
    entrepids_braintree.payment_method.config.provider.braintree:
        class: 'Entrepids\Bundle\BraintreeBundle\Method\Config\Provider\BraintreeConfigProvider'
        public: false
        arguments:
            - '@doctrine'
            - '@logger'
            - '@entrepids_braintree.factory.braintree_config'
            - '%entrepids_braintree.method.braintree%'

    entrepids_braintree.payment_method_provider.braintree:
        class: 'Entrepids\Bundle\BraintreeBundle\Method\Provider\BraintreeMethodProvider'
        public: false
        arguments:
            - '@entrepids_braintree.payment_method.config.provider.braintree'
            - '@entrepids_braintree.factory.method.braintree'
        tags:
            - { name: oro_payment.payment_method_provider }

    entrepids_braintree.payment_method_view_provider.braintree:
        class: 'Entrepids\Bundle\BraintreeBundle\Method\View\Provider\BraintreeMethodViewProvider'
        arguments:
            - '@entrepids_braintree.payment_method.config.provider.braintree'
            - '@entrepids_braintree.factory.method_view.braintree'
        tags:
            - { name: oro_payment.payment_method_view_provider }

    entrepids_braintree.method.operation.factory:
        class: Entrepids\Bundle\BraintreeBundle\Method\Operation\Factory

    entrepids_braintree.method.operation:
        abstract: true
        arguments:
            - '@session'
            - '@translator'
            - '@property_accessor'
            - '@oro_entity.doctrine_helper'




    entrepids_braintree.method.operation.capture:
        parent: entrepids_braintree.method.operation
        class: Entrepids\Bundle\BraintreeBundle\Method\Operation\CaptureOperation
        tags:
            - { name: 'braintree.operation', operation: 'capture' }

    entrepids_braintree.method.operation.charge:
        parent: entrepids_braintree.method.operation
        class: Entrepids\Bundle\BraintreeBundle\Method\Operation\ChargeOperation
        tags:
            - { name: 'braintree.operation', operation: 'charge' }

    entrepids_braintree.method.operation.purchase:
        parent: entrepids_braintree.method.operation
        class: Entrepids\Bundle\BraintreeBundle\Method\Operation\PurchaseOperation
        tags:
            - { name: 'braintree.operation', operation: 'purchase' }

    entrepids_braintree.method.operation.validate:
        parent: entrepids_braintree.method.operation
        class: Entrepids\Bundle\BraintreeBundle\Method\Operation\ValidateOperation
        tags:
            - { name: 'braintree.operation', operation: 'validate' }
