parameters:
services:
    entrepids_braintree.method:
        class: 'Entrepids\Bundle\BraintreeBundle\Method\Braintree'
        public: false
        arguments:
            - '@entrepids_braintree.method.config'
            - '@router'
            - '@entrepids_braintree.braintree.model.adapter.badapter' 
        tags:
            - { name: oro_payment.payment_method }

    entrepids_braintree.method.view:
        class: 'Entrepids\Bundle\BraintreeBundle\Method\View\BraintreeView'
        public: false
        arguments:
            - '@form.factory'
            - '@entrepids_braintree.method.config'
            - '@oro_payment.provider.payment_transaction'
            
        tags:
            - { name: oro_payment.payment_method_view }

    entrepids_braintree.method.config:
        class: 'Entrepids\Bundle\BraintreeBundle\Method\Config\BraintreeConfig'
        public: false
        arguments:
            - '@oro_config.global'
            
    entrepids_braintree.provider.credit_form_provider:
        class: 'Entrepids\Bundle\BraintreeBundle\Layout\DataProvider\CreditCardFormProvider'
        arguments:
            - '@form.factory'
            - '@router'
        tags:
            - { name: layout.data_provider, alias: entrepids_braintree_credit_card_form_provider }
 
 