parameters:
    entrepids_braintree.method.identifier_prefix.braintree: 'entrepids_braintree'
services:
    entrepids_braintree.settings.payment_action.provider:
        class: Entrepids\Bundle\BraintreeBundle\Settings\DataProvider\BasicPaymentActionsDataProvider
        
    entrepids_braintree.method.purchase.purchase_data:
        class: Entrepids\Bundle\BraintreeBundle\Method\Operation\Purchase\PurchaseData\PurchaseData    

    entrepids_braintree.settings.card_type.provider:
        class: Entrepids\Bundle\BraintreeBundle\Settings\DataProvider\BasicCardTypesDataProvider

    entrepids_braintree.settings.environment.provider:
        class: Entrepids\Bundle\BraintreeBundle\Settings\DataProvider\BasicEnvironmentDataProvider
        
    entrepids_braintree.generator.braintree_config_identifier:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%entrepids_braintree.method.identifier_prefix.braintree%'
 
    entrepids_braintree.repository.braintree_settings:
        class: 'Entrepids\Bundle\BraintreeBundle\Entity\Repository\BraintreeSettingsRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Entrepids\Bundle\BraintreeBundle\Entity\BraintreeSettings'
            
    entrepids_braintree.provider.payment_info:
        class: 'Entrepids\Bundle\BraintreeBundle\Provider\PaymentInfoProvider'
        arguments:
            - '@oro_api.doctrine_helper'
            - '@translator'
        tags:
            - { name: layout.data_provider, alias: braintree_payment_order_data }      
