parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: b2b_crm_ee_dev
    database_user: root
    database_password: null
    mailer_transport: mail
    mailer_host: 127.0.0.1
    mailer_port: null
    mailer_encryption: null
    mailer_user: null
    mailer_password: null
    websocket_bind_address: 0.0.0.0
    websocket_bind_port: 8080
    websocket_frontend_host: '*'
    websocket_frontend_port: 8080
    websocket_backend_host: '*'
    websocket_backend_port: 8080
    search_engine_name: orm
    search_engine_host: 127.0.0.1
    search_engine_port: null
    search_engine_index_name: oro_search
    search_engine_username: null
    search_engine_password: null
    search_engine_ssl_verification: null
    search_engine_ssl_cert: null
    search_engine_ssl_cert_password: null
    search_engine_ssl_key: null
    search_engine_ssl_key_password: null
    web_backend_prefix: /admin
    session_handler: session.handler.native_file
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    installed: '2017-03-02T12:45:32+00:00'
    assets_version: 895a7b6f
    assets_version_strategy: time_hash
    enterprise_licence: null
    message_queue_transport: dbal
    message_queue_transport_config: null
