parameters:
  aligent_braintree.integration.type: 'aligent_braintree'

services:
  Aligent\BraintreeBundle\Integration\BraintreeChannelType:
    class: 'Aligent\BraintreeBundle\Integration\BraintreeChannelType'
    public: true
    tags:
      - { name: oro_integration.channel, type: '%aligent_braintree.integration.type%' }

  Aligent\BraintreeBundle\Integration\BraintreeTransport:
    class: 'Aligent\BraintreeBundle\Integration\BraintreeTransport'
    public: false
    tags:
      - { name: oro_integration.transport, type: '%aligent_braintree.integration.type%', channel_type: '%aligent_braintree.integration.type%' }