aliases:
  aligentbraintree/js/app/views/single-page-checkout-form-view: aligentbraintree/js/app/views/single-page-checkout-form-view
  aligentbraintree/js/app/components/braintree-method-component$: aligentbraintree/js/app/components/braintree-method-component
  aligentbraintree/js/app/components/order-review-component$: aligentbraintree/js/app/components/order-review-component
  braintree-web-drop-in$: npmassets/braintree-web-drop-in

map:
  '*':
    orocheckout/js/app/views/single-page-checkout-form-view: aligentbraintree/js/app/views/single-page-checkout-form-view
  aligentbraintree/js/app/views/single-page-checkout-form-view:
    orocheckout/js/app/views/single-page-checkout-form-view: orocheckout/js/app/views/single-page-checkout-form-view

dynamic-imports:
  aligentbraintree:
    - aligentbraintree/js/app/components/braintree-method-component
    - aligentbraintree/js/app/components/order-review-component
    - braintree-web-drop-in
