system_configuration:
    groups:
        braintree:
            title: entrepids.braintree.system_configuration.groups.braintree.title
        braintree_display:
            title: entrepids.braintree.system_configuration.groups.display_options.title
        braintree_account_details:
            title: entrepids.braintree.system_configuration.groups.account_details.title 
        braintree_credit_card:
            title: entrepids.braintree.system_configuration.groups.credit_card.title
        braintree_capture:
            title: entrepids.braintree.system_configuration.groups.capture.title
        braintree_integretion_type:
            title: entrepids.braintree.system_configuration.groups.integration_type.title
        braintree_features:
            title: entrepids.braintree.system_configuration.groups.features.title    
    fields:
        braintree.braintree_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 100
            options:
                label: entrepids.braintree.system_configuration.fields.enabled.label

        braintree.braintree_label:
            data_type: string
            type: text
            priority: 90
            options:
                label: oro.payment.system_configuration.fields.label.label
                tooltip: oro.payment.system_configuration.fields.label.tooltip
                constraints:
                    - NotBlank: ~

        braintree.braintree_short_label:
            data_type: string
            type: text
            priority: 90
            options:
                label: oro.payment.system_configuration.fields.short_label.label
                tooltip: oro.payment.system_configuration.fields.short_label.tooltip
                constraints:
                    - NotBlank: ~

        braintree.braintree_sort_order:
            data_type: string
            type: text
            priority: 80
            options:
                label: entrepids.braintree.system_configuration.fields.sort_order.label
                constraints:
                    - Oro\Bundle\ValidationBundle\Validator\Constraints\Integer: ~

        braintree.braintree_allowed_countries:
            data_type: string
            type: choice
            priority: 70
            options:
                label: oro.payment.system_configuration.fields.allowed_countries.label
                required: true
                constraints:
                    - NotBlank: ~
                choice_translation_domain: messages
                choices:
                    all: oro.payment.system_configuration.fields.allowed_countries.all
                    selected: oro.payment.system_configuration.fields.allowed_countries.selected
                attr:
                    'data-page-component-module': 'oropayment/js/app/components/config-hide-fields-component'
                    'data-dependency-id': 'braintree_allowed_countries'

        braintree.braintree_selected_countries:
            data_type: string
            type: oro_locale_country
            priority: 60
            options:
                label: oro.payment.system_configuration.fields.selected_countries.label
                multiple: true
                attr:
                    'data-depends-on-field': 'braintree_allowed_countries'
                    'data-depends-on-field-value': 'selected'

        braintree.braintree_allowed_currencies:
            data_type: array
            type: oro_currency_selection
            priority: 60
            options:
                label: oro.pricing.system_configuration.fields.enabled_currencies.label
                required: true
                multiple: true
                constraints:
                    - NotBlank: ~

        braintree.braintree_allowed_cc_types:
            data_type: string
            type: choice
            priority: 40
            options:
                label: entrepids.braintree.system_configuration.fields.allowed_cc_types.label
                required: true
                constraints:
                    - NotBlank: ~
                choice_translation_domain: messages
                multiple: true
                choices:
                    visa: entrepids.braintree.system_configuration.fields.allowed_cc_types.visa
                    mastercard: entrepids.braintree.system_configuration.fields.allowed_cc_types.mastercard
                    discover: entrepids.braintree.system_configuration.fields.allowed_cc_types.discover
                    american_express: entrepids.braintree.system_configuration.fields.allowed_cc_types.american_express

        braintree.braintree_environment_types:
            data_type: string
            type: choice
            priority: 39
            options:
                label: entrepids.braintree.system_configuration.fields.environment_types.label
                required: true
                constraints:
                    - NotBlank: ~
                choice_translation_domain: messages
                multiple: false
                choices:
                    sandbox: entrepids.braintree.system_configuration.fields.environment_types.sandbox
                    production: entrepids.braintree.system_configuration.fields.environment_types.production

        braintree.braintree_sandbox_merch_id:
            data_type: string
            type: text
            priority: 38
            options:
                label: entrepids.braintree.system_configuration.fields.account_details.sandbox_merch_id.label  
                
        braintree.braintree_sandbox_merch_account_id:
            data_type: string
            type: text
            priority: 37
            options:
                label: entrepids.braintree.system_configuration.fields.account_details.sandbox_merch_account_id.label 
                
        braintree.braintree_sandbox_merch_public_key:
            data_type: string
            type: text
            priority: 36
            options:
                label: entrepids.braintree.system_configuration.fields.account_details.sandbox_merch_public_key.label  
                
        braintree.braintree_sandbox_merch_private_key:
            data_type: string
            type: text
            priority: 36
            options:
                label: entrepids.braintree.system_configuration.fields.account_details.sandbox_merch_private_key.label 
                
        braintree.braintree_credit_card_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 35
            options:
                label: entrepids.braintree.system_configuration.fields.credit_card.credit_card_enabled.label 
                
        braintree.braintree_credit_card_title:
            data_type: string
            type: text
            priority: 34
            options:
                label: entrepids.braintree.system_configuration.fields.credit_card.credit_card_title.label                                                                            
    tree:
        system_configuration:
            commerce:
                children:
                    payment:
                        priority: 400
                        children:
                            braintree:
                                priority: 70
                                children:
                                    braintree_display:
                                        priority: 100
                                        children:
                                            - braintree.braintree_enabled
                                            - braintree.braintree_label
                                            - braintree.braintree_short_label
                                            - braintree.braintree_sort_order
                                            - braintree.braintree_allowed_countries
                                            - braintree.braintree_selected_countries
                                            - braintree.braintree_allowed_currencies
                                            - braintree.braintree_allowed_cc_types
                                    braintree_account_details:
                                        priority: 90
                                        children:
                                            - braintree.braintree_environment_types
                                            - braintree.braintree_sandbox_merch_id
                                            - braintree.braintree_sandbox_merch_account_id
                                            - braintree.braintree_sandbox_merch_public_key
                                            - braintree.braintree_sandbox_merch_private_key
                                    braintree_credit_card:
                                        priority: 89
                                        children:
                                            - braintree.braintree_credit_card_enabled
                                            - braintree.braintree_credit_card_title

