system_configuration:
    groups:
        collect_on_delivery:
            title: oro.collect_on_delivery.system_configuration.groups.collect_on_delivery.title
        collect_on_delivery_display:
            title: oro.collect_on_delivery.system_configuration.groups.display_options.title
    fields:
        collect_on_delivery.collect_on_delivery_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 100
            options:
                label: oro.collect_on_delivery.system_configuration.fields.enabled.label

        collect_on_delivery.collect_on_delivery_label:
            data_type: string
            type: text
            priority: 90
            options:
                label: oro.payment.system_configuration.fields.label.label
                tooltip: oro.payment.system_configuration.fields.label.tooltip
                constraints:
                    - NotBlank: ~

        collect_on_delivery.collect_on_delivery_short_label:
            data_type: string
            type: text
            priority: 90
            options:
                label: oro.payment.system_configuration.fields.short_label.label
                tooltip: oro.payment.system_configuration.fields.short_label.tooltip
                constraints:
                    - NotBlank: ~

        collect_on_delivery.collect_on_delivery_sort_order:
            data_type: string
            type: text
            priority: 80
            options:
                label: oro.collect_on_delivery.system_configuration.fields.sort_order.label
                constraints:
                    - Oro\Bundle\ValidationBundle\Validator\Constraints\Integer: ~

        collect_on_delivery.collect_on_delivery_allowed_countries:
            data_type: string
            type: choice
            priority: 70
            options:
                label: oro.payment.system_configuration.fields.allowed_countries.label
                required: true
                constraints:
                    - NotBlank: ~
                choice_translation_domain: messages
                choices:
                    all: oro.payment.system_configuration.fields.allowed_countries.all
                    selected: oro.payment.system_configuration.fields.allowed_countries.selected
                attr:
                    'data-page-component-module': 'oropayment/js/app/components/config-hide-fields-component'
                    'data-dependency-id': 'collect_on_delivery_allowed_countries'

        collect_on_delivery.collect_on_delivery_selected_countries:
            data_type: string
            type: oro_locale_country
            priority: 60
            options:
                label: oro.payment.system_configuration.fields.selected_countries.label
                multiple: true
                attr:
                    'data-depends-on-field': 'collect_on_delivery_allowed_countries'
                    'data-depends-on-field-value': 'selected'

        collect_on_delivery.collect_on_delivery_allowed_currencies:
            data_type: array
            type: oro_currency_selection
            priority: 60
            options:
                label: oro.pricing.system_configuration.fields.enabled_currencies.label
                required: true
                multiple: true
                constraints:
                    - NotBlank: ~

        collect_on_delivery.collect_on_delivery_allowed_cc_types:
            data_type: string
            type: choice
            priority: 40
            options:
                label: oro.collect_on_delivery.system_configuration.fields.allowed_cc_types.label
                required: true
                constraints:
                    - NotBlank: ~
                choice_translation_domain: messages
                multiple: true
                choices:
                    visa: oro.collect_on_delivery.system_configuration.fields.allowed_cc_types.visa
                    mastercard: oro.collect_on_delivery.system_configuration.fields.allowed_cc_types.mastercard
                    discover: oro.collect_on_delivery.system_configuration.fields.allowed_cc_types.discover
                    american_express: oro.collect_on_delivery.system_configuration.fields.allowed_cc_types.american_express
    tree:
        system_configuration:
            commerce:
                children:
                    payment:
                        priority: 400
                        children:
                            collect_on_delivery:
                                priority: 70
                                children:
                                    collect_on_delivery_display:
                                        priority: 100
                                        children:
                                            - collect_on_delivery.collect_on_delivery_enabled
                                            - collect_on_delivery.collect_on_delivery_label
                                            - collect_on_delivery.collect_on_delivery_short_label
                                            - collect_on_delivery.collect_on_delivery_sort_order
                                            - collect_on_delivery.collect_on_delivery_allowed_countries
                                            - collect_on_delivery.collect_on_delivery_selected_countries
                                            - collect_on_delivery.collect_on_delivery_allowed_currencies
                                            - collect_on_delivery.collect_on_delivery_allowed_cc_types
