parameters:
services:
    oro_collect_on_delivery.method:
        class: 'Oro\Bundle\CollectOnDelivery\CollectOnDeliveryBundle\Method\CollectOnDelivery'
        public: false
        arguments:
            - '@oro_collect_on_delivery.method.config'
        tags:
            - { name: oro_payment.payment_method }

    oro_collect_on_delivery.method.view:
        class: 'Oro\Bundle\CollectOnDelivery\CollectOnDeliveryBundle\Method\View\CollectOnDeliveryView'
        public: false
        arguments:
            - '@oro_collect_on_delivery.method.config'
        tags:
            - { name: oro_payment.payment_method_view }

    oro_collect_on_delivery.method.config:
        class: 'Oro\Bundle\CollectOnDelivery\CollectOnDeliveryBundle\Method\Config\CollectOnDeliveryConfig'
        public: false
        arguments:
            - '@oro_config.manager'